import fs from 'fs';
import path from 'path';
import os from 'os';
import { z } from 'zod';

function cosineSimilarity(vecA: number[], vecB: number[]) {
  let dotProduct = 0;
  let normA = 0;
  let normB = 0;
  for (let i = 0; i < vecA.length; i++) {
    dotProduct += vecA[i] * vecB[i];
    normA += vecA[i] ** 2;
    normB += vecB[i] ** 2;
  }
  if (normA === 0 || normB === 0) return 0;
  return dotProduct / (Math.sqrt(normA) * Math.sqrt(normB));
}

export default {
  description: "Search the local skill vault for highly relevant agent skills based on the user's task or query. Returns absolute paths to the SKILL.md files. Always read these files after receiving their paths.",
  args: {
    query: z.string().describe("The task description or query to find relevant skills for (e.g. 'deploy azure postgres')"),
  },
  async execute(args: { query: string }, context: any) {
    // IMPORTANT: Path to the index generated by build_index.ts
    const INDEX_PATH = path.join(context.worktree || process.cwd(), 'index.json');
    const LOG_PATH = path.join(os.homedir(), '.config', 'opencode', 'skill_vault.log');
    
    // Log the incoming query
    const timestamp = new Date().toISOString();
    try { fs.appendFileSync(LOG_PATH, `[${timestamp}] 🔍 QUERY RECEIVED: "${args.query}"\n`); } catch(e) {}
    
    if (!fs.existsSync(INDEX_PATH)) {
      return `Error: Skill index not found at ${INDEX_PATH}. Please run the build_index.ts script first.`;
    }

    const indexData = JSON.parse(fs.readFileSync(INDEX_PATH, 'utf-8'));
    
    try {
      // 1. Load the local model and embed the query
      // Dynamically import to handle the ESM module inside the tool execution
      const { pipeline } = await import('@xenova/transformers');
      const extractor = await pipeline('feature-extraction', 'Xenova/all-MiniLM-L6-v2');
      
      const output = await extractor(args.query, { pooling: 'mean', normalize: true });
      const queryEmbedding = Array.from(output.data);

      // 2. Calculate cosine similarity against all skills
      const scoredSkills = indexData
        .filter((skill: any) => skill.embedding && skill.embedding.length > 0)
        .map((skill: any) => ({
          ...skill,
          score: cosineSimilarity(queryEmbedding, skill.embedding),
        }));

      // 3. Sort and get top 3 matches (Pure Local Option A)
      scoredSkills.sort((a: any, b: any) => b.score - a.score);
      const topMatches = scoredSkills.slice(0, 3);

      if (topMatches.length === 0 || topMatches[0].score < 0.2) {
        try { fs.appendFileSync(LOG_PATH, `[${timestamp}] ❌ NO MATCHES FOUND (Highest score: ${scoredSkills[0]?.score || 0})\n\n`); } catch(e) {}
        return "No highly relevant skills found in the vault for this query. Proceed with general knowledge.";
      }

      let result = "Found the following highly relevant skills:\n\n";
      let logMatchStr = `[${timestamp}] ✅ MATCHES FOUND:\n`;
      for (const skill of topMatches) {
        const absolutePath = path.resolve(context.worktree || process.cwd(), skill.path);
        // Include the score for debugging/context
        result += `- ${skill.name} (Relevance: ${(skill.score * 100).toFixed(1)}%): ${absolutePath}\n`;
        logMatchStr += `    - ${skill.name} (${(skill.score * 100).toFixed(1)}%)\n`;
      }
      
      try { fs.appendFileSync(LOG_PATH, `${logMatchStr}\n`); } catch(e) {}
      
      result += "\nACTION REQUIRED: Use your Read tool immediately to read the contents of these SKILL.md files before proceeding.";
      
      return result;

    } catch (error: any) {
      try { fs.appendFileSync(LOG_PATH, `[${timestamp}] ⚠️ ERROR: ${error.message}\n\n`); } catch(e) {}
      return `Error searching skills: ${error.message}`;
    }
  }
};
