import fs from 'fs';
import path from 'path';
import os from 'os';
import { z } from 'zod';

function cosineSimilarity(vecA: number[], vecB: number[]) {
  let dotProduct = 0;
  let normA = 0;
  let normB = 0;
  for (let i = 0; i < vecA.length; i++) {
    dotProduct += vecA[i] * vecB[i];
    normA += vecA[i] ** 2;
    normB += vecB[i] ** 2;
  }
  if (normA === 0 || normB === 0) return 0;
  return dotProduct / (Math.sqrt(normA) * Math.sqrt(normB));
}

// Tier 1 lifecycle keywords for fast matching against skills in skills/
const LIFECYCLE_TRIGGERS: Record<string, string[]> = {
  'spec-driven-development': ['spec', 'specification', 'requirements', 'prd', 'plan feature', 'new project', 'new feature', 'design spec', 'write spec', 'architecture'],
  'planning-and-task-breakdown': ['plan', 'breakdown', 'tasks', 'roadmap', 'milestone', 'schedule', 'organize', 'structure work', 'task list', 'project plan'],
  'incremental-implementation': ['implement', 'build feature', 'add feature', 'development', 'coding', 'write code', 'create', 'slice', 'vertical slice'],
  'test-driven-development': ['test', 'tdd', 'testing', 'unit test', 'integration test', 'jest', 'vitest', 'pytest', 'mocha', 'coverage'],
  'debugging-and-error-recovery': ['debug', 'bug', 'error', 'fix', 'crash', 'failure', 'exception', 'broken', 'not working', 'troubleshoot'],
  'code-review-and-quality': ['review', 'pr review', 'code review', 'refactor', 'quality', 'lint', 'smell', 'improve code', 'peer review'],
  'code-simplification': ['simplify', 'cleanup', 'clean up', 'reduce complexity', 'delete code', 'remove dead code', 'streamline'],
  'security-and-hardening': ['security', 'secure', 'auth', 'authentication', 'authorization', 'owasp', 'sanitize', 'injection', 'vulnerability', 'xss', 'csrf'],
  'performance-optimization': ['performance', 'optimize', 'speed', 'fast', 'slow', 'latency', 'memory leak', 'profiling', 'benchmark', 'bundle size'],
  'frontend-ui-engineering': ['frontend', 'ui', 'react', 'vue', 'angular', 'html', 'css', 'component', 'design system', 'tailwind', 'responsive', 'accessibility'],
  'api-and-interface-design': ['api', 'rest', 'graphql', 'endpoint', 'swagger', 'openapi', 'contract', 'interface', 'dto', 'schema'],
  'source-driven-development': ['documentation', 'docs', 'official docs', 'framework version', 'verify source', 'cite', 'reference'],
  'context-engineering': ['context', 'prompt engineering', 'mcp', 'system prompt', 'custom instructions', 'rules file', 'context packing'],
  'browser-testing-with-devtools': ['devtools', 'chrome', 'browser', 'e2e', 'playwright', 'cypress', 'selenium', 'dom', 'console', 'network tab'],
  'git-workflow-and-versioning': ['git', 'commit', 'branch', 'merge', 'rebase', 'workflow', 'semantic version', 'changelog', 'release'],
  'ci-cd-and-automation': ['ci', 'cd', 'pipeline', 'github actions', 'gitlab ci', 'jenkins', 'deploy', 'docker', 'kubernetes', 'automation'],
  'shipping-and-launch': ['ship', 'launch', 'production', 'prod', 'release', 'deploy to prod', 'go live', 'rollout', 'rollback', 'feature flag'],
  'deprecation-and-migration': ['deprecate', 'migration', 'sunset', 'remove', 'legacy', 'upgrade', 'migrate', 'breaking change'],
  'documentation-and-adrs': ['adr', 'architecture decision', 'design doc', 'runbook', 'readme', 'api doc', 'inline doc', 'comment'],
  'idea-refine': ['ideate', 'brainstorm', 'idea', 'concept', 'refine', 'explore', 'discover', 'prototype'],
};

function detectLifecycleMatches(query: string): string[] {
  const lower = query.toLowerCase();
  const matches: string[] = [];
  for (const [skill, triggers] of Object.entries(LIFECYCLE_TRIGGERS)) {
    for (const trigger of triggers) {
      if (lower.includes(trigger)) {
        matches.push(skill);
        break;
      }
    }
  }
  return [...new Set(matches)]; // dedupe
}

export default {
  description: "Search the local skill vault using a two-tier system. Tier 1 (skills/) contains 20 production-grade lifecycle skills (specs, testing, reviews, shipping). Tier 2 (organized-skills/) contains 2,300+ domain skills (Azure, quantum, etc.). Returns absolute paths to SKILL.md files. Always read these files after receiving their paths.",
  args: {
    query: z.string().describe("The task description or query to find relevant skills for (e.g., 'build a new feature with tests' or 'deploy azure postgres')"),
  },
  async execute(args: { query: string }, context: any) {
    // IMPORTANT: Path to the index generated by build_index.ts
    const INDEX_PATH = '/Users/luisvalencia/Documents/ClaudeCodeRepos/index.json';
    const LOG_PATH = path.join(os.homedir(), '.config', 'opencode', 'skill_vault.log');

    // Log the incoming query
    const timestamp = new Date().toISOString();
    try { fs.appendFileSync(LOG_PATH, `[${timestamp}] 🔍 QUERY RECEIVED: "${args.query}"\n`); } catch(e) {}

    if (!fs.existsSync(INDEX_PATH)) {
      return `Error: Skill index not found at ${INDEX_PATH}. Please run the build_index.ts script first.`;
    }

    const indexData = JSON.parse(fs.readFileSync(INDEX_PATH, 'utf-8'));
    const results: { tag: string; skill: any }[] = [];

    // ============================================================
    // PASS 1 — TIER 1: Fast Lifecycle Skill Detection (skills/)
    // ============================================================
    const lifecycleMatches = detectLifecycleMatches(args.query);
    for (const skillName of lifecycleMatches) {
      const entry = indexData.find((s: any) => s.name === skillName && s.path.startsWith('skills/'));
      if (entry) {
        results.push({ tag: 'LIFECYCLE', skill: { ...entry, score: 1.0 } });
      }
    }

    // ============================================================
    // PASS 2 — TIER 2: Domain RAG Search (organized-skills/)
    // ============================================================
    try {
      const { pipeline } = await import('@xenova/transformers');
      const extractor = await pipeline('feature-extraction', 'Xenova/all-MiniLM-L6-v2');

      const output = await extractor(args.query, { pooling: 'mean', normalize: true });
      const queryEmbedding = Array.from(output.data as Float32Array);

      const scoredSkills = indexData
        .filter((skill: any) => skill.embedding && skill.embedding.length > 0)
        .map((skill: any) => ({
          ...skill,
          score: cosineSimilarity(queryEmbedding, skill.embedding),
        }));

      scoredSkills.sort((a: any, b: any) => b.score - a.score);

      // Add top domain matches, but skip skills already found in Pass 1
      const alreadyAdded = new Set(results.map(r => r.skill.name));
      for (const skill of scoredSkills) {
        if (skill.score < 0.2) break;
        if (alreadyAdded.has(skill.name)) continue;
        results.push({ tag: 'DOMAIN', skill });
        if (results.filter(r => r.tag === 'DOMAIN').length >= 3) break;
      }

    } catch (error: any) {
      try { fs.appendFileSync(LOG_PATH, `[${timestamp}] ⚠️ EMBEDDING ERROR: ${error.message}\n`); } catch(e) {}
    }

    // ============================================================
    // Format Results
    // ============================================================
    if (results.length === 0) {
      try { fs.appendFileSync(LOG_PATH, `[${timestamp}] ❌ NO MATCHES FOUND\n\n`); } catch(e) {}
      return "No highly relevant skills found in the vault for this query. Proceed with general knowledge.";
    }

    let outputStr = "Found the following highly relevant skills:\n\n";
    let logMatchStr = `[${timestamp}] ✅ MATCHES FOUND:\n`;
    for (const { tag, skill } of results) {
        const absolutePath = path.resolve('/Users/luisvalencia/Documents/ClaudeCodeRepos', skill.path);
      const scoreStr = (skill.score * 100).toFixed(1);
      outputStr += `[${tag}] ${skill.name} (Relevance: ${scoreStr}%): ${absolutePath}\n`;
      logMatchStr += `    [${tag}] ${skill.name} (${scoreStr}%)\n`;
    }

    try { fs.appendFileSync(LOG_PATH, `${logMatchStr}\n`); } catch(e) {}

    outputStr += "\nACTION REQUIRED: Use your Read tool immediately to read the contents of these SKILL.md files before proceeding.";

    return outputStr;
  }
};
